simple Repl, setup test file for Parsers
PolyglotSymposium/pyrgos pull request #14
Opened 2022-05-24 14:57 UTC by tscales

2022-05-25 14:00 UTC, Kazark requested changes
Super start---you are a rockstar Haskell programmer Ty! 😜

2022-05-25 14:00 UTC, Kazark commented on hinmil/test/ParserSpec.hs
> +main :: IO ()
I don't think there should be a `main` method in this file---there should only be one for the whole `test` project (and I think it already is there)

2022-05-25 14:00 UTC, Kazark commented on hinmil/test/ParserSpec.hs
> +main :: IO ()
Basically, it should be auto-generated in `Spec.hs`

2022-05-25 14:00 UTC, Kazark commented on hinmil/test/SubstitutionsSpec.hs
> +main :: IO ()
No, this shouldn't be here

2022-05-25 14:00 UTC, Kazark commented on hinmil/test/Spec.hs
> +{-# OPTIONS_GHC -Wno-missing-export-lists #-}
When you address a couple of the other comments, this may not be needed

2022-05-25 22:55 UTC, tscales commented on hinmil/test/Spec.hs
> +{-# OPTIONS_GHC -Wno-missing-export-lists #-}
still isn't happy.

```
    The export item ‘module Main’ is missing an export list
  |         
1 | {-# OPTIONS_GHC -F -pgmF hspec-discover #-}
  | ^   
```

2022-05-26 00:43 UTC, Kazark commented on hinmil/test/Spec.hs
> +{-# OPTIONS_GHC -Wno-missing-export-lists #-}
I eat my words.

2022-05-26 00:45 UTC, Kazark approved these changes
SCALES

2022-05-26 00:45 UTC, Kazark commented on hinmil/test/ParserSpec.hs
> +import Test.Hspec.Megaparsec
Wow, I didn't even notice this and `shouldParse` during my first review. This rings a bell from long ago. Good work.

2022-05-26 00:45 UTC, merged